"""initial schema

Revision ID: 7f4613f8a00b
Revises: 
Create Date: 2026-05-18 19:01:29.902556

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '7f4613f8a00b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('primary_first_name', sa.String(length=80), nullable=False),
    sa.Column('primary_last_name', sa.String(length=80), nullable=False),
    sa.Column('primary_dob', sa.Date(), nullable=False),
    sa.Column('primary_ssn_last4_enc', sa.String(length=255), nullable=False),
    sa.Column('spouse_first_name', sa.String(length=80), nullable=True),
    sa.Column('spouse_last_name', sa.String(length=80), nullable=True),
    sa.Column('spouse_dob', sa.Date(), nullable=True),
    sa.Column('spouse_ssn_last4_enc', sa.String(length=255), nullable=True),
    sa.Column('monthly_inflow', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('monthly_outflow_budget', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('private_reserve_target_override', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('floor_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'PLANNER', 'ASSISTANT', name='user_role'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('owner', sa.Enum('PRIMARY', 'SPOUSE', 'JOINT', name='account_owner'), nullable=False),
    sa.Column('category', sa.Enum('RETIREMENT', 'NON_RETIREMENT', name='account_category'), nullable=False),
    sa.Column('account_type', sa.Enum('IRA', 'ROTH_IRA', 'K401', 'PENSION', 'BROKERAGE', 'JOINT', 'OTHER', name='account_type'), nullable=False),
    sa.Column('institution', sa.String(length=120), nullable=False),
    sa.Column('last_four', sa.String(length=4), nullable=True),
    sa.Column('label', sa.String(length=120), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_accounts_client_id'), ['client_id'], unique=False)

    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('actor_user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=80), nullable=False),
    sa.Column('target_type', sa.String(length=80), nullable=True),
    sa.Column('target_id', sa.Integer(), nullable=True),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_logs_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_actor_user_id'), ['actor_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_created_at'), ['created_at'], unique=False)

    op.create_table('insurance_deductibles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=120), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('insurance_deductibles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_insurance_deductibles_client_id'), ['client_id'], unique=False)

    op.create_table('liabilities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('liability_type', sa.Enum('MORTGAGE', 'AUTO_LOAN', 'STUDENT_LOAN', 'CREDIT_CARD', 'HELOC', 'OTHER', name='liability_type'), nullable=False),
    sa.Column('label', sa.String(length=120), nullable=False),
    sa.Column('interest_rate', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('last_four', sa.String(length=4), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('liabilities', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_liabilities_client_id'), ['client_id'], unique=False)

    op.create_table('reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('generated_by_user_id', sa.Integer(), nullable=True),
    sa.Column('period_label', sa.String(length=60), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'FINAL', name='report_status'), nullable=False),
    sa.Column('totals_json', sa.JSON(), nullable=False),
    sa.Column('finalized_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['generated_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reports_client_id'), ['client_id'], unique=False)

    op.create_table('trust_properties',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=120), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=False),
    sa.Column('notes', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('trust_properties', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_trust_properties_client_id'), ['client_id'], unique=False)

    op.create_table('report_balances',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('report_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.Enum('ACCOUNT', 'LIABILITY', 'TRUST', 'PRIVATE_RESERVE', 'SCHWAB_CASH', name='report_balance_kind'), nullable=False),
    sa.Column('target_id', sa.Integer(), nullable=True),
    sa.Column('field_key', sa.String(length=80), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('report_balances', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_report_balances_report_id'), ['report_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('report_balances', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_report_balances_report_id'))

    op.drop_table('report_balances')
    with op.batch_alter_table('trust_properties', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_trust_properties_client_id'))

    op.drop_table('trust_properties')
    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reports_client_id'))

    op.drop_table('reports')
    with op.batch_alter_table('liabilities', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_liabilities_client_id'))

    op.drop_table('liabilities')
    with op.batch_alter_table('insurance_deductibles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_insurance_deductibles_client_id'))

    op.drop_table('insurance_deductibles')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_logs_created_at'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_actor_user_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_action'))

    op.drop_table('audit_logs')
    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_accounts_client_id'))

    op.drop_table('accounts')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    op.drop_table('clients')
    # ### end Alembic commands ###
